from bst_ import bst_
import matplotlib.pyplot as plt
import networkx as nx
from networkx.drawing.nx_agraph import graphviz_layout
obj=bst_()
root= obj.insert(None,15)
obj.insert(root,10)
obj.insert(root,25)
obj.insert(root,6)
obj.insert(root,14)
obj.insert(root,20)
obj.insert(root,60)
a1=root
a2=a1.left
a3=a1.right
a4=a2.left
a5=a2.right
a6=a3.left
a7=a3.right
print("Root Node is:")
print(a1.data)
print("left child of node is:")
print(a1.left.data)
print("right child of node is:")
print(a1.right.data)
print("Node is:")
print(a2.data)
print("left child of node is:")
print(a2.left.data)
print("right child of node is:")
print(a2.right.data)
print("Node is:")
print(a3.data)
print("left child of node is:")
print(a3.left.data)
print("right child of node is:")
print(a3.right.data)
print("Node is:")
print(a4.data)
print("left child of node is:")
print(a4.left)
print("right child of node is:")
print(a4.right)
print("Node is:")
print(a5.data)
print("left child of node is:")
print(a5.left)
print("right child of node is:")
print(a5.right)
print("Node is:")
print(a6.data)
print("left child of node is:")
print(a6.left)
print("right child of node is:")
print(a6.right)
print("Node is:")
print(a7.data)
print("left child of node is:")
print(a7.left)
print("right child of node is:")
print(a7.right)
print("\n Preorder")
obj.preOrder(root)
print("\n Postorder")
obj.postOrder(root)
print("\n Inorder")
obj.inOrder(root)
print("\n count of nodes")
count=obj.count_nodes(root)
print(count)
print("\n Height")
h=int(obj.height(root))
print(h)
print("\n printing leafs")
obj.print_leaf(root)
print("\n Check BST")
t=obj.checkBST(root)
print(t)
obj.plot_tree(root)
obj.delete_node(root,15)
obj.plot_tree(root)